# Generated by Django 4.1.7 on 2023-03-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoría',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoría_superior_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jerarquia.categoría')),
            ],
        ),
        migrations.CreateModel(
            name='JerarquíaCategorías',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferior_categoría_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inf', to='jerarquia.categoría')),
                ('superior_categoría_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sup', to='jerarquia.categoría')),
            ],
        ),
    ]
