# Generated by Django 4.1.7 on 2023-03-02 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerarquia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposiciónObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoría', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jerarquia.categoría')),
                ('objeto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jerarquia.objeto')),
            ],
        ),
    ]
