# Generated by Django 4.1.7 on 2023-03-02 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerarquia', '0002_composiciónobjeto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jerarquíacategorías',
            options={'verbose_name': 'jerarquía de categoría', 'verbose_name_plural': 'jerarquía de categorías'},
        ),
        migrations.AlterField(
            model_name='objeto',
            name='categoría_superior_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jerarquia.jerarquíacategorías'),
        ),
    ]
