# Generated by Django 4.1.7 on 2023-03-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerarquia', '0004_remove_composiciónobjeto_categoría_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composiciónobjeto',
            name='superior_categoría_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_sup', to='jerarquia.categoría'),
        ),
    ]
