# Generated by Django 4.1.7 on 2023-03-02 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerarquia', '0005_alter_composiciónobjeto_superior_categoría_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composiciónobjeto',
            name='inferior_categoría_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_inf', to='jerarquia.jerarquíacategorías'),
        ),
        migrations.AlterField(
            model_name='composiciónobjeto',
            name='superior_categoría_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_sup', to='jerarquia.jerarquíacategorías'),
        ),
    ]
