# Generated by Django 4.1.7 on 2023-03-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerarquia', '0006_alter_composiciónobjeto_inferior_categoría_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composiciónobjeto',
            old_name='superior_categoría_id',
            new_name='categoría',
        ),
        migrations.RemoveField(
            model_name='composiciónobjeto',
            name='inferior_categoría_id',
        ),
        migrations.AddField(
            model_name='composiciónobjeto',
            name='descripción',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
